buy_line:
  - '&e%amount%&fx&e%item%&f'
  - '&fBuy for &e%cost%&f$'
sell_line:
  - '&e%amount%&fx&e%item%&f'
  - '&fSell for &e%cost%&f$'

hologram_correction_rate: 600

error_no_permission: '&cYou do not have access to this command'

toggle_on_sign: '&7ChestShops you make now get holograms placed above its &esigns'
toggle_on_block: '&7ChestShops you make now get holograms placed above the &eblock &7it''s placed against'

toggle_icon_on: '&7ChestShops you make have an item icon &eadded &7to them'
toggle_icon_off: '&7ChestShops you make &eno longer &7receive items'

toggle_holos_on: '&7ChestShops you make &ereceive &7a hologram on top upon creation'
toggle_holos_off: '&7ChestShops you make &eno longer receive&7 a hologram on top upon creation'