name: Chestshopholos
version: 1.0
main: me.athlaeos.chestshopholos.Main
api-version: 1.16
depend: [ChestShop]
description: Adds holograms to chestshops
commands:
  chestshopholo:
    description: Base command for the ChestShopHolos plugin
    aliases: [holos]

permissions:
  shopholo.toggle:
    description: Allows the user access to all /chestshopholo toggle commands
    default: op
  shopholo.toggle.icons:
    description: Allows the user access to /chestshopholo toggle_item_icon, which allows the user to toggle item icons on chestshops they make
    default: op
  shopholo.toggle.holograms:
    description: Allows the user access to /chestshopholo toggle_holos, which allows the user to toggle holograms on chestshops they make
    default: op
  shopholo.toggle.placement:
    description: Allows the user access to /chestshopholo toggle_placement, which allows the user to toggle if holograms appear over the shop's sign or over the block they're placed against
    default: op

